import { NextResponse } from "next/server"
import bcrypt from "bcryptjs"
import { connectToDatabase } from "@/lib/mongodb"
import User from "@/models/User"
import Doctor from "@/models/Doctor"
import { notifyAdmins } from "@/lib/notifications"

export const dynamic = "force-dynamic"

export async function GET() {
  try {
    await connectToDatabase()

    // Fetch doctors from MongoDB
    let doctorList = await Doctor.find({}).sort({ createdAt: -1 })

    if (doctorList.length === 0) {
      return NextResponse.json({
        success: true,
        count: 0,
        doctors: [],
      })
    }

    // Attach email and phone from linked user if missing on Doctor
    const populated = await Promise.all(
      doctorList.map(async (doc) => {
        const docObj = doc.toObject()
        if (!docObj.email || !docObj.phone) {
          const u = await User.findOne({
            $or: [{ doctorId: docObj.id }, { email: docObj.email }],
          })
          if (u) {
            docObj.email = docObj.email || u.email
            docObj.phone = docObj.phone || u.phone
          }
        }
        if (!docObj.status) docObj.status = "Active"
        return docObj
      }),
    )

    return NextResponse.json({
      success: true,
      count: populated.length,
      doctors: populated,
    })
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        error: error.message || "Failed to fetch doctors",
        doctors: [],
      },
      { status: 200 },
    )
  }
}

// Helper to generate unique @medislot.com email based on doctor name
async function generateUniqueDoctorEmail(name) {
  let base = (name || "")
    .toLowerCase()
    .replace(/^dr\.?\s*/i, "")
    .replace(/[^a-z0-9]/g, "")
    .trim()

  if (!base) {
    base = "doctor"
  }

  let candidate = `${base}@medislot.com`
  let counter = 2

  while (true) {
    const userMatch = await User.findOne({ email: candidate })
    const doctorMatch = await Doctor.findOne({ email: candidate })

    if (!userMatch && !doctorMatch) {
      return candidate
    }

    candidate = `${base}${counter}@medislot.com`
    counter++
  }
}

export async function POST(req) {
  try {
    await connectToDatabase()

    const body = await req.json()
    const {
      name,
      phone,
      specialization,
      department,
      experience,
      consultationDuration,
      hospital,
      password,
      confirmPassword,
      availableDays,
      startTime,
      endTime,
    } = body

    // 1. Validation: Required fields (email is auto-generated by backend)
    if (!name?.trim()) {
      return NextResponse.json(
        {
          success: false,
          message: "Doctor full name is required.",
          error: "Doctor full name is required.",
        },
        { status: 400 },
      )
    }
    if (!phone?.trim()) {
      return NextResponse.json(
        {
          success: false,
          message: "Phone number is required.",
          error: "Phone number is required.",
        },
        { status: 400 },
      )
    }
    if (!specialization?.trim()) {
      return NextResponse.json(
        {
          success: false,
          message: "Specialization is required.",
          error: "Specialization is required.",
        },
        { status: 400 },
      )
    }
    if (!department?.trim()) {
      return NextResponse.json(
        {
          success: false,
          message: "Department is required.",
          error: "Department is required.",
        },
        { status: 400 },
      )
    }
    if (!password) {
      return NextResponse.json(
        {
          success: false,
          message: "Password is required.",
          error: "Password is required.",
        },
        { status: 400 },
      )
    }

    // Password validations
    if (password.length < 6) {
      return NextResponse.json(
        {
          success: false,
          message: "Password must be at least 6 characters long.",
          error: "Password must be at least 6 characters long.",
        },
        { status: 400 },
      )
    }
    if (confirmPassword !== undefined && password !== confirmPassword) {
      return NextResponse.json(
        {
          success: false,
          message: "Passwords do not match.",
          error: "Passwords do not match.",
        },
        { status: 400 },
      )
    }

    // 2. Use provided email or automatically generate unique @medislot.com doctor email
    const cleanEmail = body.email?.trim()
      ? body.email.trim().toLowerCase()
      : await generateUniqueDoctorEmail(name)

    // 3. Hash temporary password with bcrypt
    const saltRounds = 10
    const hashedPassword = await bcrypt.hash(password, saltRounds)

    // Generate unique doctor ID
    const docCount = await Doctor.countDocuments()
    const docId = `d_${Date.now().toString().slice(-6)}_${docCount + 1}`

    const formattedName = name.trim().startsWith("Dr.")
      ? name.trim()
      : `Dr. ${name.trim()}`
    const initials =
      formattedName
        .replace(/^Dr\.\s*/i, "")
        .split(" ")
        .filter(Boolean)
        .map((n) => n[0])
        .join("")
        .toUpperCase()
        .slice(0, 2) || "DR"

    const daysList =
      Array.isArray(availableDays) && availableDays.length > 0
        ? availableDays
        : ["Monday", "Tuesday", "Thursday", "Friday"]

    const sTime = startTime?.trim() || "10:00 AM"
    const eTime = endTime?.trim() || "01:00 PM"
    const expNum = Number(experience) || 1
    const durationNum = Number(consultationDuration) || 30
    const hosp = hospital?.trim() || "MediSlot Hospital"

    // Build weekly schedule
    const weeklySchedule = {}
    for (const day of daysList) {
      weeklySchedule[day] = `${sTime} – ${eTime}`
    }

    // 4. Save doctor login user record in MongoDB users collection
    const newUser = await User.create({
      name: formattedName,
      email: cleanEmail,
      password: hashedPassword,
      role: "doctor",
      phone: phone.trim(),
      specialization: specialization.trim(),
      department: department.trim(),
      experience: expNum,
      consultationDuration: durationNum,
      hospital: hosp,
      availableDays: daysList,
      startTime: sTime,
      endTime: eTime,
      status: "Active",
      doctorId: docId,
      avatar: initials,
      lastLogin: new Date(),
    })

    // 5. Save doctor record in doctors collection
    const newDoctor = await Doctor.create({
      id: docId,
      name: formattedName,
      email: cleanEmail,
      phone: phone.trim(),
      specialization: specialization.trim(),
      department: department.trim(),
      experience: expNum,
      consultationDuration: durationNum,
      hospital: hosp,
      availableDays: daysList,
      startTime: sTime,
      endTime: eTime,
      rating: 4.8,
      reviewCount: 0,
      availableToday: true,
      avatar: initials,
      weeklySchedule,
      status: "Active",
      userId: newUser._id,
    })

    const doctorDisplayName = newDoctor.name?.trim().startsWith("Dr.")
      ? newDoctor.name.trim()
      : `Dr. ${newDoctor.name?.trim() || "Doctor"}`

    await notifyAdmins({
      type: "doctor_added",
      title: "New Doctor Added",
      message: `${doctorDisplayName} has been added to MediSlot.`,
      relatedId: newDoctor.id || newDoctor._id.toString(),
      relatedType: "doctor",
    })

    // 6. Return response (NEVER return password)
    return NextResponse.json(
      {
        success: true,
        message:
          "Doctor account created successfully. The doctor can now log in using the registered email and password.",
        doctor: {
          id: newDoctor.id,
          name: newDoctor.name,
          email: newDoctor.email,
          phone: newDoctor.phone,
          specialization: newDoctor.specialization,
          department: newDoctor.department,
          experience: newDoctor.experience,
          consultationDuration: newDoctor.consultationDuration,
          hospital: newDoctor.hospital,
          role: "doctor",
          availableDays: newDoctor.availableDays,
          startTime: newDoctor.startTime,
          endTime: newDoctor.endTime,
          status: newDoctor.status,
          userId: newUser._id.toString(),
        },
      },
      { status: 201 },
    )
  } catch (error) {
    return NextResponse.json(
      {
        success: false,
        message: error.message || "Failed to create doctor account",
        error: error.message || "Failed to create doctor account",
      },
      { status: 500 },
    )
  }
}
