"use client"

// Modals state

// Success state after creating a doctor

// Add Doctor Form State (Email is automatically generated on backend)

// Edit Doctor Form State

// Handle available days toggle for Add Form

// Handle available days toggle for Edit Form

// 1. Submit Add Doctor Form (Email auto-generated by backend)

// Client validation (no email required from user)

// Success: Show confirmation modal with doctor information and generated email (NO password shown)

// Reset form

// 2. Open View Doctor

// 3. Open Edit Doctor

// Submit Edit Doctor Form

// 4. Open Delete Doctor

// Confirm Delete Doctor

// Filter doctors

import { useState, useEffect, Suspense } from "react"

import { useSearchParams } from "next/navigation"

import {
  Plus,
  Search,
  Edit2,
  Trash2,
  Eye,
  X,
  CheckCircle,
  AlertCircle,
  User,
  Mail,
  Phone,
  Briefcase,
  Building2,
  Clock,
  Calendar,
  Lock,
  ShieldCheck,
  Hospital,
  Filter,
} from "lucide-react"

import StatusBadge from "@/components/ui/StatusBadge"

import AdminLayout from "@/components/layout/AdminLayout"

const DAYS_OF_WEEK = [
  "Monday",

  "Tuesday",

  "Wednesday",

  "Thursday",

  "Friday",

  "Saturday",

  "Sunday",
]

const avatarColors = {
  AS: "bg-teal-600",

  PN: "bg-violet-600",

  RK: "bg-blue-600",

  SM: "bg-rose-600",

  VP: "bg-amber-600",

  AR: "bg-emerald-600",

  DR: "bg-teal-700",
}

function DoctorsContent() {
  const searchParams = useSearchParams()

  const [doctorsList, setDoctorsList] = useState([])

  const [loading, setLoading] = useState(true)

  const [query, setQuery] = useState("")

  const [deptFilter, setDeptFilter] = useState("All")

  const [showAddModal, setShowAddModal] = useState(false)

  const [showViewModal, setShowViewModal] = useState(false)

  const [showEditModal, setShowEditModal] = useState(false)

  const [showDeleteModal, setShowDeleteModal] = useState(false)

  const [selectedDoctor, setSelectedDoctor] = useState(null)

  const [submitting, setSubmitting] = useState(false)

  const [formError, setFormError] = useState("")

  const [createdDoctorSuccess, setCreatedDoctorSuccess] = useState(null)

  const [formData, setFormData] = useState({
    name: "",

    phone: "",

    specialization: "",

    department: "Cardiology",

    experience: "5",

    consultationDuration: "30",

    hospital: "MediSlot Hospital",

    password: "",

    confirmPassword: "",

    availableDays: ["Monday", "Tuesday", "Thursday", "Friday"],

    startTime: "10:00 AM",

    endTime: "01:00 PM",
  })

  const [editFormData, setEditFormData] = useState({
    id: "",

    name: "",

    email: "",

    phone: "",

    specialization: "",

    department: "",

    experience: "",

    consultationDuration: "30",

    hospital: "",

    availableDays: [],

    startTime: "10:00 AM",

    endTime: "01:00 PM",

    status: "Active",
  })

  const fetchDoctors = async () => {
    try {
      setLoading(true)

      const res = await fetch("/api/doctors")

      const data = await res.json()

      if (data.success && Array.isArray(data.doctors)) {
        setDoctorsList(data.doctors)
      } else {
        setDoctorsList([])
      }
    } catch (err) {
      console.warn("Failed to fetch doctors from API:", err)

      setDoctorsList([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchDoctors()
  }, [])

  useEffect(() => {
    if (searchParams.get("action") === "add") {
      setShowAddModal(true)
    }
  }, [searchParams])

  const toggleDay = (day) => {
    setFormData((prev) => {
      const exists = prev.availableDays.includes(day)

      const nextDays = exists
        ? prev.availableDays.filter(
            (d) => d !== day,
          )
        : [...prev.availableDays, day]

      return { ...prev, availableDays: nextDays }
    })
  }

  const toggleEditDay = (day) => {
    setEditFormData((prev) => {
      const exists = prev.availableDays.includes(day)

      const nextDays = exists
        ? prev.availableDays.filter(
            (d) => d !== day,
          )
        : [...prev.availableDays, day]

      return { ...prev, availableDays: nextDays }
    })
  }

  const handleAddDoctorSubmit = async (e) => {
    e.preventDefault()

    setFormError("")

    if (!formData.name.trim()) return setFormError("Doctor name is required.")

    if (!formData.phone.trim()) return setFormError("Phone number is required.")

    if (!formData.specialization.trim())
      return setFormError("Specialization is required.")

    if (!formData.department.trim())
      return setFormError("Department is required.")

    if (!formData.password) return setFormError("Password is required.")

    if (formData.password.length < 6)
      return setFormError("Password must be at least 6 characters.")

    if (formData.password !== formData.confirmPassword)
      return setFormError("Passwords do not match.")

    if (formData.availableDays.length === 0)
      return setFormError("Please select at least one available day.")

    setSubmitting(true)

    try {
      const res = await fetch("/api/doctors", {
        method: "POST",

        headers: { "Content-Type": "application/json" },

        body: JSON.stringify(formData),
      })

      const data = await res.json()

      if (!res.ok || !data.success) {
        setFormError(
          data.message || data.error || "Failed to create doctor account.",
        )

        setSubmitting(false)

        return
      }

      setCreatedDoctorSuccess(data.doctor)

      setShowAddModal(false)

      setFormData({
        name: "",

        phone: "",

        specialization: "",

        department: "Cardiology",

        experience: "5",

        consultationDuration: "30",

        hospital: "MediSlot Hospital",

        password: "",

        confirmPassword: "",

        availableDays: ["Monday", "Tuesday", "Thursday", "Friday"],

        startTime: "10:00 AM",

        endTime: "01:00 PM",
      })

      fetchDoctors()
    } catch (err) {
      setFormError("Network error while creating doctor. Please try again.")
    } finally {
      setSubmitting(false)
    }
  }

  const handleOpenView = (doctor) => {
    setSelectedDoctor(doctor)

    setShowViewModal(true)
  }

  const handleOpenEdit = (doctor) => {
    setSelectedDoctor(doctor)

    setEditFormData({
      id: doctor.id,

      name: doctor.name || "",

      email: doctor.email || "",

      phone: doctor.phone || "+91 98765 43210",

      specialization: doctor.specialization || "",

      department: doctor.department || "",

      experience:
        doctor.experience !== undefined ? String(doctor.experience) : "5",

      consultationDuration:
        doctor.consultationDuration !== undefined
          ? String(doctor.consultationDuration)
          : "30",

      hospital: doctor.hospital || "MediSlot Hospital",

      availableDays: Array.isArray(doctor.availableDays)
        ? doctor.availableDays
        : ["Monday", "Tuesday", "Thursday", "Friday"],

      startTime: doctor.startTime || "10:00 AM",

      endTime: doctor.endTime || "01:00 PM",

      status: doctor.status || "Active",
    })

    setFormError("")

    setShowEditModal(true)
  }

  const handleEditDoctorSubmit = async (e) => {
    e.preventDefault()

    setFormError("")

    setSubmitting(true)

    try {
      const res = await fetch(`/api/admin/doctors/${editFormData.id}`, {
        method: "PUT",

        headers: { "Content-Type": "application/json" },

        body: JSON.stringify(editFormData),
      })

      const data = await res.json()

      if (!res.ok || !data.success) {
        setFormError(
          data.error || "Failed to update doctor.",
        )

        setSubmitting(false)

        return
      }

      setShowEditModal(false)

      fetchDoctors()
    } catch (err) {
      setFormError("Failed to update doctor.")
    } finally {
      setSubmitting(false)
    }
  }

  const handleOpenDelete = (doctor) => {
    setSelectedDoctor(doctor)

    setShowDeleteModal(true)
  }

  const handleConfirmDelete = async () => {
    if (!selectedDoctor) return

    setSubmitting(true)

    try {
      const res = await fetch(`/api/admin/doctors/${selectedDoctor.id}`, {
        method: "DELETE",
      })

      const data = await res.json()

      if (data.success) {
        setShowDeleteModal(false)

        fetchDoctors()
      } else {
        alert(
          data.error || "Failed to delete doctor.",
        )
      }
    } catch (err) {
      alert("Error deleting doctor.")
    } finally {
      setSubmitting(false)
    }
  }

  const departments = [
    "All",

    ...new Set(doctorsList.map((d) => d.department).filter(Boolean)),
  ]

  const filtered = doctorsList.filter((d) => {
    const matchesDept = deptFilter === "All" || d.department === deptFilter

    const matchesQuery =
      d.name?.toLowerCase().includes(query.toLowerCase()) ||
      d.email?.toLowerCase().includes(query.toLowerCase()) ||
      d.department?.toLowerCase().includes(query.toLowerCase()) ||
      d.specialization?.toLowerCase().includes(query.toLowerCase())

    return matchesDept && matchesQuery
  })

  return (
    <AdminLayout>
      <div className="space-y-6">
        {}
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1
              className="text-2xl font-bold text-slate-900"
              style={{ fontFamily: "'DM Sans', sans-serif" }}
            >
              Doctor Management
            </h1>
            <p className="text-slate-500 text-sm mt-1">
              Add new doctors, manage login credentials, schedules, and clinical
              profiles
            </p>
          </div>
          <button
            onClick={() => {
              setFormError("")

              setShowAddModal(true)
            }}
            className="flex items-center gap-2 bg-teal-600 hover:bg-teal-700 text-white font-semibold text-sm px-4 py-2.5 rounded-lg transition-colors cursor-pointer shadow-sm active:scale-[0.99]"
          >
            <Plus className="w-4 h-4" /> Add Doctor
          </button>
        </div>

        {}
        <div className="grid sm:grid-cols-3 gap-3">
          <div className="sm:col-span-2 flex items-center gap-2 bg-white border border-slate-200 rounded-xl px-4 py-2.5 shadow-xs">
            <Search className="w-4 h-4 text-slate-400 flex-shrink-0" />
            <input
              type="text"
              placeholder="Search by doctor name, email, specialization, or department..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="flex-1 text-sm text-slate-700 bg-transparent outline-none"
            />
            {query && (
              <button
                onClick={() => setQuery("")}
                className="text-xs text-slate-400 hover:text-slate-600"
              >
                Clear
              </button>
            )}
          </div>

          <div className="flex items-center gap-2 bg-white border border-slate-200 rounded-xl px-3 py-2 shadow-xs">
            <Filter className="w-4 h-4 text-slate-400 flex-shrink-0" />
            <select
              value={deptFilter}
              onChange={(e) => setDeptFilter(e.target.value)}
              className="w-full text-sm text-slate-700 bg-transparent outline-none cursor-pointer"
            >
              {departments.map((dept) => (
                <option key={dept} value={dept}>
                  {dept === "All" ? "All Departments" : dept}
                </option>
              ))}
            </select>
          </div>
        </div>

        {}
        <div className="bg-white rounded-xl border border-slate-100 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-100">
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Doctor
                  </th>
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Email
                  </th>
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Specialization
                  </th>
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Department
                  </th>
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Experience
                  </th>
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Hospital
                  </th>
                  <th className="px-4 py-3.5 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-4 py-3.5 text-right text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {loading ? (
                  <tr>
                    <td
                      colSpan={8}
                      className="px-4 py-12 text-center text-slate-400 text-sm"
                    >
                      <div className="inline-block w-6 h-6 border-2 border-teal-600 border-t-transparent rounded-full animate-spin mr-2 align-middle"></div>
                      Loading doctors directory...
                    </td>
                  </tr>
                ) : filtered.length === 0 ? (
                  <tr>
                    <td
                      colSpan={8}
                      className="px-4 py-16 text-center text-slate-400 text-sm"
                    >
                      {doctorsList.length === 0 ? (
                        <div className="flex flex-col items-center justify-center py-4">
                          <div className="w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center text-slate-400 mb-3">
                            <Briefcase className="w-6 h-6 text-slate-400" />
                          </div>
                          <p className="text-slate-800 font-semibold text-base mb-1">
                            No doctors registered yet
                          </p>
                          <p className="text-slate-400 text-xs mb-4 max-w-sm">
                            All previous doctors have been cleared. You can
                            manually register your hospital doctors using the
                            button below.
                          </p>
                          <button
                            onClick={() => setShowAddModal(true)}
                            className="inline-flex items-center gap-2 px-4 py-2 bg-teal-600 hover:bg-teal-700 text-white rounded-lg text-xs font-semibold cursor-pointer shadow-sm transition-colors"
                          >
                            <Plus className="w-4 h-4" /> Add Doctor
                          </button>
                        </div>
                      ) : (
                        "No doctors found matching your criteria."
                      )}
                    </td>
                  </tr>
                ) : (
                  filtered.map((d) => {
                    const initials =
                      d.avatar ||
                      d.name

                        ?.replace(/^Dr\.\s*/i, "")

                        .split(" ")

                        .map((n) => n[0])

                        .join("")

                        .toUpperCase()

                        .slice(0, 2) ||
                      "DR"

                    const emailDisplay =
                      d.email ||
                      `${d.name.toLowerCase().replace(/[^a-z]/g, "")}@medislot.com`

                    return (
                      <tr
                        key={d.id}
                        className="hover:bg-slate-50/60 transition-colors"
                      >
                        <td className="px-4 py-3.5">
                          <div className="flex items-center gap-3">
                            <div
                              className={`w-9 h-9 ${avatarColors[d.avatar] || "bg-teal-600"} rounded-xl flex items-center justify-center text-white text-xs font-bold flex-shrink-0 shadow-xs`}
                            >
                              {initials}
                            </div>
                            <div>
                              <p className="text-sm font-semibold text-slate-900 whitespace-nowrap">
                                {d.name}
                              </p>
                              <p className="text-xs text-slate-400">
                                {d.phone || "+91 98765 43210"}
                              </p>
                            </div>
                          </div>
                        </td>
                        <td className="px-4 py-3.5 text-sm text-slate-600 whitespace-nowrap font-mono text-xs">
                          {emailDisplay}
                        </td>
                        <td className="px-4 py-3.5 text-sm text-slate-700 whitespace-nowrap font-medium">
                          {d.specialization}
                        </td>
                        <td className="px-4 py-3.5 text-sm text-slate-600 whitespace-nowrap">
                          <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
                            {d.department}
                          </span>
                        </td>
                        <td className="px-4 py-3.5 text-sm text-slate-600 whitespace-nowrap font-medium">
                          {d.experience}{" "}
                          {Number(d.experience) === 1 ? "Year" : "Years"}
                        </td>
                        <td className="px-4 py-3.5 text-sm text-slate-600 whitespace-nowrap">
                          {d.hospital || "City Hospital"}
                        </td>
                        <td className="px-4 py-3.5 whitespace-nowrap">
                          <StatusBadge
                            status={(d.status || "Active").toLowerCase()}
                          />
                        </td>
                        <td className="px-4 py-3.5 text-right whitespace-nowrap">
                          <div className="flex items-center justify-end gap-1.5">
                            <button
                              onClick={() => handleOpenView(d)}
                              className="px-2.5 py-1.5 text-teal-700 hover:bg-teal-50 rounded-lg text-xs font-semibold transition-colors cursor-pointer flex items-center gap-1"
                              title="View Details"
                            >
                              <Eye className="w-3.5 h-3.5" /> View
                            </button>
                            <button
                              onClick={() => handleOpenEdit(d)}
                              className="p-1.5 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors cursor-pointer"
                              title="Edit Doctor"
                            >
                              <Edit2 className="w-3.5 h-3.5" />
                            </button>
                            <button
                              onClick={() => handleOpenDelete(d)}
                              className="p-1.5 text-red-500 hover:bg-red-50 rounded-lg transition-colors cursor-pointer"
                              title="Delete Doctor"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    )
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>

        {}
        {}
        {}
        {showAddModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
            <div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl border border-slate-100 overflow-hidden my-8 animate-in fade-in zoom-in-95 duration-150">
              <div className="p-5 bg-teal-600 text-white flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-bold">
                    Add Doctor & Create Login Account
                  </h2>
                  <p className="text-xs text-teal-100 mt-0.5">
                    Provision doctor credentials and clinical practice profile
                    in MediSlot
                  </p>
                </div>
                <button
                  onClick={() => setShowAddModal(false)}
                  className="p-1.5 text-white/80 hover:text-white hover:bg-white/10 rounded-lg cursor-pointer transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form
                onSubmit={handleAddDoctorSubmit}
                className="p-6 space-y-6 max-h-[80vh] overflow-y-auto"
              >
                {formError && (
                  <div className="p-3.5 bg-red-50 border border-red-200 rounded-xl text-red-700 text-xs font-semibold flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-red-500 flex-shrink-0" />
                    <span>{formError}</span>
                  </div>
                )}

                {}
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-teal-700 flex items-center gap-1.5 pb-2 border-b border-slate-100 mb-3">
                    <User className="w-4 h-4" /> 1. Personal Information
                  </h3>
                  <div className="grid sm:grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Doctor Name *
                      </label>
                      <input
                        type="text"
                        required
                        placeholder="Dr. Amit Sharma"
                        value={formData.name}
                        onChange={(e) =>
                          setFormData({ ...formData, name: e.target.value })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                      />
                    </div>
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Phone Number *
                      </label>
                      <input
                        type="tel"
                        required
                        placeholder="9876543210"
                        value={formData.phone}
                        onChange={(e) =>
                          setFormData({ ...formData, phone: e.target.value })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                      />
                    </div>
                  </div>
                </div>

                {}
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-teal-700 flex items-center gap-1.5 pb-2 border-b border-slate-100 mb-3">
                    <Briefcase className="w-4 h-4" /> 2. Professional
                    Information
                  </h3>
                  <div className="grid sm:grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Specialization *
                      </label>
                      <input
                        type="text"
                        required
                        placeholder="Cardiologist"
                        value={formData.specialization}
                        onChange={(e) =>
                          setFormData({
                            ...formData,

                            specialization: e.target.value,
                          })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                      />
                    </div>
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Department *
                      </label>
                      <select
                        value={formData.department}
                        onChange={(e) =>
                          setFormData({
                            ...formData,

                            department: e.target.value,
                          })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500 bg-white"
                      >
                        <option value="Cardiology">Cardiology</option>
                        <option value="Dermatology">Dermatology</option>
                        <option value="Orthopedics">Orthopedics</option>
                        <option value="Pediatrics">Pediatrics</option>
                        <option value="Neurology">Neurology</option>
                        <option value="General Medicine">
                          General Medicine
                        </option>
                        <option value="Gynecology">Gynecology</option>
                        <option value="ENT">ENT</option>
                      </select>
                    </div>
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Experience (Years) *
                      </label>
                      <input
                        type="number"
                        min="0"
                        max="60"
                        required
                        placeholder="8"
                        value={formData.experience}
                        onChange={(e) =>
                          setFormData({
                            ...formData,

                            experience: e.target.value,
                          })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                      />
                    </div>
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Consultation Duration (Minutes)
                      </label>
                      <select
                        value={formData.consultationDuration}
                        onChange={(e) =>
                          setFormData({
                            ...formData,

                            consultationDuration: e.target.value,
                          })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500 bg-white"
                      >
                        <option value="15">15 Minutes</option>
                        <option value="20">20 Minutes</option>
                        <option value="30">30 Minutes (Recommended)</option>
                        <option value="45">45 Minutes</option>
                        <option value="60">60 Minutes</option>
                      </select>
                    </div>
                    <div className="sm:col-span-2">
                      <label className="text-xs font-bold text-slate-700 block mb-1">
                        Hospital / Clinic Name
                      </label>
                      <input
                        type="text"
                        placeholder="City Hospital"
                        value={formData.hospital}
                        onChange={(e) =>
                          setFormData({ ...formData, hospital: e.target.value })
                        }
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                      />
                    </div>
                  </div>
                </div>

                {}
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-teal-700 flex items-center gap-1.5 pb-2 border-b border-slate-100 mb-3">
                    <Lock className="w-4 h-4" /> 3. Login Information
                  </h3>
                  <div className="space-y-3">
                    <div className="bg-teal-50/80 border border-teal-200/80 rounded-xl p-3.5">
                      <div className="flex items-center justify-between gap-2">
                        <div className="flex items-center gap-2 text-teal-900 font-semibold text-xs">
                          <Mail className="w-4 h-4 text-teal-600 shrink-0" />
                          <span>Official MediSlot Email:</span>
                        </div>
                        <span className="text-[10px] font-bold uppercase tracking-wider bg-teal-600 text-white px-2 py-0.5 rounded-full">
                          Auto-Generated
                        </span>
                      </div>
                      <p className="font-mono text-sm font-bold text-teal-950 mt-1.5 break-all">
                        {formData.name.trim() ? (
                          `${
                            formData.name

                              .trim()

                              .toLowerCase()

                              .replace(/^dr\.?\s*/i, "")

                              .replace(/[^a-z0-9]/g, "") || "doctor"
                          }@medislot.com`
                        ) : (
                          <span className="text-teal-600 font-sans text-xs italic font-normal">
                            Enter Doctor Name above to preview generated
                            @medislot.com email
                          </span>
                        )}
                      </p>
                      <p className="text-[11px] text-teal-700/90 mt-1">
                        The backend automatically provisions this official
                        @medislot.com login email. Duplicate names are assigned
                        unique numeric suffixes.
                      </p>
                    </div>

                    <div className="grid sm:grid-cols-2 gap-3">
                      <div>
                        <label className="text-xs font-bold text-slate-700 block mb-1">
                          Password *
                        </label>
                        <input
                          type="password"
                          required
                          placeholder="••••••••"
                          value={formData.password}
                          onChange={(e) =>
                            setFormData({
                              ...formData,

                              password: e.target.value,
                            })
                          }
                          className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                        />
                        <p className="text-[10px] text-slate-400 mt-1">
                          Min 6 chars. Hashed with bcrypt before storage.
                        </p>
                      </div>
                      <div>
                        <label className="text-xs font-bold text-slate-700 block mb-1">
                          Confirm Password *
                        </label>
                        <input
                          type="password"
                          required
                          placeholder="••••••••"
                          value={formData.confirmPassword}
                          onChange={(e) =>
                            setFormData({
                              ...formData,

                              confirmPassword: e.target.value,
                            })
                          }
                          className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                        />
                      </div>
                    </div>
                  </div>
                </div>

                {}
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-teal-700 flex items-center gap-1.5 pb-2 border-b border-slate-100 mb-3">
                    <Clock className="w-4 h-4" /> 4. Availability
                  </h3>
                  <div className="space-y-3">
                    <div>
                      <label className="text-xs font-bold text-slate-700 block mb-1.5">
                        Available Days *
                      </label>
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                        {DAYS_OF_WEEK.map((day) => {
                          const isSelected =
                            formData.availableDays.includes(day)

                          return (
                            <button
                              key={day}
                              type="button"
                              onClick={() => toggleDay(day)}
                              className={`py-1.5 px-3 text-xs font-medium rounded-lg border transition-all cursor-pointer text-left flex items-center justify-between ${
                                isSelected
                                  ? "bg-teal-50 border-teal-500 text-teal-800 font-bold"
                                  : "bg-white border-slate-200 text-slate-600 hover:border-slate-300"
                              }`}
                            >
                              <span>{day}</span>
                              {isSelected && (
                                <span className="text-teal-600 font-bold">
                                  ✓
                                </span>
                              )}
                            </button>
                          )
                        })}
                      </div>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="text-xs font-bold text-slate-700 block mb-1">
                          Start Time *
                        </label>
                        <input
                          type="text"
                          required
                          placeholder="10:00 AM"
                          value={formData.startTime}
                          onChange={(e) =>
                            setFormData({
                              ...formData,

                              startTime: e.target.value,
                            })
                          }
                          className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                        />
                      </div>
                      <div>
                        <label className="text-xs font-bold text-slate-700 block mb-1">
                          End Time *
                        </label>
                        <input
                          type="text"
                          required
                          placeholder="01:00 PM"
                          value={formData.endTime}
                          onChange={(e) =>
                            setFormData({
                              ...formData,

                              endTime: e.target.value,
                            })
                          }
                          className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                        />
                      </div>
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t border-slate-100 flex gap-3">
                  <button
                    type="button"
                    onClick={() => setShowAddModal(false)}
                    className="flex-1 py-2.5 px-4 rounded-lg border border-slate-200 text-slate-700 text-sm font-semibold hover:bg-slate-50 transition-colors cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="flex-1 py-2.5 px-4 rounded-lg bg-teal-600 hover:bg-teal-700 disabled:opacity-60 text-white text-sm font-semibold transition-colors cursor-pointer shadow-sm flex items-center justify-center gap-2"
                  >
                    {submitting ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Creating Account...
                      </>
                    ) : (
                      "Create Doctor Account"
                    )}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {}
        {}
        {}
        {createdDoctorSuccess && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
            <div className="bg-white rounded-2xl max-w-md w-full shadow-2xl border border-slate-100 p-6 space-y-5 animate-in fade-in zoom-in-95">
              <div className="text-center space-y-2">
                <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto">
                  <CheckCircle className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-bold text-slate-900">
                  Doctor added successfully.
                </h3>
                <p className="text-xs text-slate-500">
                  Doctor credentials have been saved in MongoDB. The official
                  email has been automatically generated.
                </p>
              </div>

              <div className="bg-slate-50 rounded-xl p-4 border border-slate-100 space-y-3 text-sm">
                <div className="flex justify-between items-center pb-2 border-b border-slate-200/60">
                  <span className="text-xs text-slate-500 font-semibold uppercase tracking-wider">
                    Doctor Name:
                  </span>
                  <span className="font-bold text-slate-900">
                    {createdDoctorSuccess.name}
                  </span>
                </div>
                <div className="flex justify-between items-center pb-2 border-b border-slate-200/60">
                  <span className="text-xs text-slate-500 font-semibold uppercase tracking-wider">
                    Doctor Email:
                  </span>
                  <span className="font-mono text-xs font-bold text-teal-800 bg-teal-50 px-2 py-1 rounded border border-teal-200">
                    {createdDoctorSuccess.email}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-xs text-slate-500 font-medium">
                    Specialization:
                  </span>
                  <span className="text-slate-700 font-medium">
                    {createdDoctorSuccess.specialization} (
                    {createdDoctorSuccess.department})
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-xs text-slate-500 font-medium">
                    Hospital:
                  </span>
                  <span className="text-slate-700 font-medium">
                    {createdDoctorSuccess.hospital || "City Hospital"}
                  </span>
                </div>
              </div>

              <div className="p-3.5 bg-teal-50 border border-teal-200 rounded-xl text-teal-900 text-xs space-y-1">
                <p className="font-bold uppercase tracking-wider text-teal-800 text-[11px]">
                  Doctor Login:
                </p>
                <p className="font-medium text-slate-800">
                  Use this email with the password created by Admin.
                </p>
              </div>

              <button
                onClick={() => setCreatedDoctorSuccess(null)}
                className="w-full bg-teal-600 hover:bg-teal-700 text-white font-semibold py-2.5 rounded-xl text-sm transition-colors cursor-pointer shadow-sm"
              >
                Done
              </button>
            </div>
          </div>
        )}

        {}
        {}
        {}
        {showViewModal && selectedDoctor && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
            <div className="bg-white rounded-2xl max-w-lg w-full shadow-2xl border border-slate-100 overflow-hidden my-8 animate-in fade-in zoom-in-95">
              <div className="p-5 bg-slate-900 text-white flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-teal-600 rounded-xl flex items-center justify-center text-white font-bold text-sm">
                    {selectedDoctor.avatar || "DR"}
                  </div>
                  <div>
                    <h3 className="font-bold text-base">
                      {selectedDoctor.name}
                    </h3>
                    <p className="text-xs text-slate-400">
                      {selectedDoctor.specialization} •{" "}
                      {selectedDoctor.department}
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setShowViewModal(false)}
                  className="p-1 text-slate-400 hover:text-white rounded-lg cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="p-6 space-y-5">
                {}
                <div>
                  <h4 className="text-xs font-bold text-teal-700 uppercase tracking-wider pb-1.5 border-b border-slate-100 mb-2.5 flex items-center gap-1.5">
                    <User className="w-3.5 h-3.5" /> Doctor Information
                  </h4>
                  <div className="grid grid-cols-2 gap-y-2 text-xs">
                    <div>
                      <span className="text-slate-400 block">Name:</span>
                      <span className="font-semibold text-slate-800 text-sm">
                        {selectedDoctor.name}
                      </span>
                    </div>
                    <div>
                      <span className="text-slate-400 block">Phone:</span>
                      <span className="font-medium text-slate-800">
                        {selectedDoctor.phone || "+91 98765 43210"}
                      </span>
                    </div>
                    <div>
                      <span className="text-slate-400 block">
                        Specialization:
                      </span>
                      <span className="font-medium text-slate-800">
                        {selectedDoctor.specialization}
                      </span>
                    </div>
                    <div>
                      <span className="text-slate-400 block">Department:</span>
                      <span className="font-medium text-slate-800">
                        {selectedDoctor.department}
                      </span>
                    </div>
                    <div>
                      <span className="text-slate-400 block">Experience:</span>
                      <span className="font-medium text-slate-800">
                        {selectedDoctor.experience} Years
                      </span>
                    </div>
                    <div>
                      <span className="text-slate-400 block">Hospital:</span>
                      <span className="font-medium text-slate-800">
                        {selectedDoctor.hospital || "MediSlot Hospital"}
                      </span>
                    </div>
                  </div>
                </div>

                {}
                <div>
                  <h4 className="text-xs font-bold text-teal-700 uppercase tracking-wider pb-1.5 border-b border-slate-100 mb-2.5 flex items-center gap-1.5">
                    <ShieldCheck className="w-3.5 h-3.5" /> Login Information
                  </h4>
                  <div className="bg-slate-50 p-3.5 rounded-xl border border-slate-100 space-y-2 text-xs">
                    <div className="flex justify-between items-center">
                      <span className="text-slate-500 font-medium">
                        Login Email:
                      </span>
                      <span className="font-mono text-xs font-semibold text-teal-700">
                        {selectedDoctor.email || "Not configured"}
                      </span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-slate-500 font-medium">
                        Account Status:
                      </span>
                      <span className="px-2 py-0.5 rounded-full text-[11px] font-bold bg-emerald-100 text-emerald-800">
                        {selectedDoctor.status || "Active"}
                      </span>
                    </div>
                    <div className="flex justify-between items-center">
                      <span className="text-slate-500 font-medium">Role:</span>
                      <span className="font-semibold text-slate-800">
                        Doctor
                      </span>
                    </div>
                  </div>
                </div>

                {}
                <div>
                  <h4 className="text-xs font-bold text-teal-700 uppercase tracking-wider pb-1.5 border-b border-slate-100 mb-2.5 flex items-center gap-1.5">
                    <Calendar className="w-3.5 h-3.5" /> Availability
                  </h4>
                  <div className="space-y-2 text-xs">
                    <div>
                      <span className="text-slate-400 block mb-1">
                        Available Days:
                      </span>
                      <div className="flex flex-wrap gap-1">
                        {(Array.isArray(selectedDoctor.availableDays)
                          ? selectedDoctor.availableDays
                          : ["Monday", "Tuesday", "Thursday", "Friday"]
                        )

                          .map((day) => (
                            <span
                              key={day}
                              className="px-2 py-0.5 bg-teal-50 text-teal-700 border border-teal-100 rounded-md font-medium text-[11px]"
                            >
                              {day}
                            </span>
                          ))}
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-2 pt-1">
                      <div>
                        <span className="text-slate-400 block">
                          Start Time:
                        </span>
                        <span className="font-semibold text-slate-800">
                          {selectedDoctor.startTime || "10:00 AM"}
                        </span>
                      </div>
                      <div>
                        <span className="text-slate-400 block">End Time:</span>
                        <span className="font-semibold text-slate-800">
                          {selectedDoctor.endTime || "01:00 PM"}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="pt-2">
                  <button
                    onClick={() => setShowViewModal(false)}
                    className="w-full py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-800 font-semibold rounded-xl text-sm transition-colors cursor-pointer"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {}
        {}
        {}
        {showEditModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
            <div className="bg-white rounded-2xl max-w-xl w-full shadow-2xl border border-slate-100 overflow-hidden my-8 animate-in fade-in zoom-in-95">
              <div className="p-5 bg-teal-700 text-white flex items-center justify-between">
                <div>
                  <h3 className="font-bold text-base">Edit Doctor Profile</h3>
                  <p className="text-xs text-teal-100">
                    Preserves doctor credentials and user ID association
                  </p>
                </div>
                <button
                  onClick={() => setShowEditModal(false)}
                  className="p-1 text-white/80 hover:text-white rounded-lg cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <form
                onSubmit={handleEditDoctorSubmit}
                className="p-6 space-y-4 max-h-[80vh] overflow-y-auto"
              >
                {formError && (
                  <div className="p-3 bg-red-50 text-red-700 border border-red-200 rounded-lg text-xs font-semibold">
                    {formError}
                  </div>
                )}

                <div className="grid sm:grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Full Name
                    </label>
                    <input
                      type="text"
                      required
                      value={editFormData.name}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          name: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Phone Number
                    </label>
                    <input
                      type="text"
                      required
                      value={editFormData.phone}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          phone: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Specialization
                    </label>
                    <input
                      type="text"
                      required
                      value={editFormData.specialization}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          specialization: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Department
                    </label>
                    <input
                      type="text"
                      required
                      value={editFormData.department}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          department: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Experience (Years)
                    </label>
                    <input
                      type="number"
                      value={editFormData.experience}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          experience: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Consultation Duration (Min)
                    </label>
                    <select
                      value={editFormData.consultationDuration}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          consultationDuration: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500 bg-white"
                    >
                      <option value="15">15 Minutes</option>
                      <option value="20">20 Minutes</option>
                      <option value="30">30 Minutes</option>
                      <option value="45">45 Minutes</option>
                      <option value="60">60 Minutes</option>
                    </select>
                  </div>
                  <div className="sm:col-span-2">
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Hospital / Clinic
                    </label>
                    <input
                      type="text"
                      value={editFormData.hospital}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          hospital: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1.5">
                    Available Days
                  </label>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                    {DAYS_OF_WEEK.map((day) => {
                      const isSelected =
                        editFormData.availableDays.includes(day)

                      return (
                        <button
                          key={day}
                          type="button"
                          onClick={() => toggleEditDay(day)}
                          className={`py-1.5 px-3 text-xs font-medium rounded-lg border transition-all cursor-pointer flex items-center justify-between ${
                            isSelected
                              ? "bg-teal-50 border-teal-500 text-teal-800 font-bold"
                              : "bg-white border-slate-200 text-slate-600 hover:border-slate-300"
                          }`}
                        >
                          <span>{day}</span>
                          {isSelected && (
                            <span className="text-teal-600 font-bold">✓</span>
                          )}
                        </button>
                      )
                    })}
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      Start Time
                    </label>
                    <input
                      type="text"
                      value={editFormData.startTime}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          startTime: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-bold text-slate-700 block mb-1">
                      End Time
                    </label>
                    <input
                      type="text"
                      value={editFormData.endTime}
                      onChange={(e) =>
                        setEditFormData({
                          ...editFormData,

                          endTime: e.target.value,
                        })
                      }
                      className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:border-teal-500"
                    />
                  </div>
                </div>

                <div className="pt-3 border-t border-slate-100 flex gap-3">
                  <button
                    type="button"
                    onClick={() => setShowEditModal(false)}
                    className="flex-1 py-2.5 px-4 rounded-lg border border-slate-200 text-slate-700 text-sm font-semibold hover:bg-slate-50 transition-colors cursor-pointer"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={submitting}
                    className="flex-1 py-2.5 px-4 rounded-lg bg-teal-600 hover:bg-teal-700 text-white text-sm font-semibold transition-colors cursor-pointer shadow-sm"
                  >
                    {submitting ? "Saving..." : "Save Changes"}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {}
        {}
        {}
        {showDeleteModal && selectedDoctor && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
            <div className="bg-white rounded-2xl max-w-md w-full shadow-2xl border border-slate-100 p-6 space-y-4 animate-in fade-in zoom-in-95">
              <div className="w-12 h-12 bg-red-100 text-red-600 rounded-full flex items-center justify-center mx-auto">
                <Trash2 className="w-6 h-6" />
              </div>

              <div className="text-center space-y-1">
                <h3 className="text-lg font-bold text-slate-900">
                  Are you sure you want to delete this doctor?
                </h3>
                <p className="text-xs text-slate-500">
                  This action will permanently delete{" "}
                  <strong>{selectedDoctor.name}</strong> and remove their login
                  credentials from MongoDB. This action cannot be undone.
                </p>
              </div>

              <div className="p-3 bg-slate-50 rounded-xl text-xs space-y-1 text-slate-600 border border-slate-100">
                <p>
                  <strong>Doctor:</strong> {selectedDoctor.name}
                </p>
                <p>
                  <strong>Email:</strong> {selectedDoctor.email || "N/A"}
                </p>
                <p>
                  <strong>Department:</strong> {selectedDoctor.department}
                </p>
              </div>

              <div className="flex gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setShowDeleteModal(false)}
                  className="flex-1 py-2.5 px-4 rounded-lg border border-slate-200 text-slate-700 text-sm font-semibold hover:bg-slate-50 transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleConfirmDelete}
                  disabled={submitting}
                  className="flex-1 py-2.5 px-4 rounded-lg bg-red-600 hover:bg-red-700 text-white text-sm font-semibold transition-colors cursor-pointer shadow-sm disabled:opacity-60"
                >
                  {submitting ? "Deleting..." : "Delete Doctor"}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </AdminLayout>
  )
}

export default function AdminDoctorsPage() {
  return (
    <Suspense
      fallback={
        <div className="p-8 text-slate-400">Loading Doctors Portal...</div>
      }
    >
      <DoctorsContent />
    </Suspense>
  )
}
